stages:
  - lint
  - build
  # - test
  - deploy

lint:
  stage: lint
  script:
    - docker run --rm -v $(pwd):/data yangm97/luacheck || [ "$?" -le "1" ]

build:
  stage: build
  variables:
    IMAGE: $CI_REGISTRY_IMAGE
    TAG: $CI_COMMIT_REF_SLUG
  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker-compose build
    - docker-compose push
  only:
    - staging
    - production

deploy:
  environment:
    name: $CI_COMMIT_REF_SLUG
  tags:
    - manager
  stage: deploy
  variables:
    IMAGE: $CI_REGISTRY_IMAGE
    TAG: $CI_COMMIT_REF_SLUG
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker stack deploy --with-registry-auth $CI_COMMIT_REF_SLUG -c docker-compose.yml
  only:
    - staging
    - production
