blank_issues_enabled: true
contact_links:
  - name: Winx Support
    url: https://t.me/WinxSupport
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: https://Winx.tech/
    about: Documentation for getting started with bot.
